### ISSUE TITLE
cannot deploy on localhost

### ISSUE THREAD

**Issue by pg07codes** [fossasia/accounts.susi.ai#448] opened 2018-08-13 03:14 UTC
site is not able to start on localhost , gives the error as shown on `npm run start`

![image](https://user-images.githubusercontent.com/34238240/44011187-bb39bfc0-9ed4-11e8-8a7f-04a8efbb6ecc.png)

kindly help me out.

PS: if its not the apt place to ask , where should one ask such questions.Thankks

**Comment by fragm3** [comment] 2018-08-17 17:39
Duplicate of: https://github.com/fossasia/accounts.susi.ai/issues/435

**Closed** 2018-08-18 04:45 UTC
